name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code (Only /server)
      uses: actions/checkout@v3
      with:
        sparse-checkout: server
        sparse-checkout-cone-mode: false

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR with Maven
      run: |
        cd server
        mvn clean package -DskipTests

    - name: Setup SSH Key
      run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

    - name: Copy JAR to EC2
      run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem \
          server/target/Eshop-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/shopit/server/app.jar

    - name: Restart Application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_HOST }} <<EOF
          sudo systemctl stop shopit
          sudo cp /home/ubuntu/shopit/server/app.jar /home/ubuntu/shopit/server/backup/app-$(date +%F-%H-%M-%S).jar
          sudo systemctl start shopit
        EOF
