name: Deploy React App to AWS S3 🚀

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Build React App
        run: |
          cd client
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync client/dist s3://shopit-frontend --delete

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id EVZ16RMJKRUSC --paths "/*"

